sonar.projectKey=webshop
sonar.host.url=http://localhost:9000
sonar.token=sqp_08314586a0d7555d1dcded916b38f91401c2d7ca
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-report.xml
sonar.sources=src
sonar.inclusions=**
sonar.qualitygate.wait=true

sonar.scm.disabled=true
# sonar.scm.provider=git
sonar.qualitygate.ignoreSmallChanges=false

sonar.cpd.minimumLines=2
sonar.cpd.minimumTokens=2
# Forçar análise de duplicações
sonar.cpd.javascript.minimumLines=2
sonar.cpd.javascript.minimumTokens=2
sonar.cpd.typescript.minimumLines=2
sonar.cpd.typescript.minimumTokens=2

# --------------------------
# Quality Gate
# --------------------------
# A regra de zero duplicações deve ser configurada no SonarQube Web UI:
# Duplicated Lines (%) <= 0%
# Assim qualquer duplicação fará o Quality Gate falhar
