name: Validate

on:
  workflow_dispatch:  # só para rodar localmente
  workflow_call: # permite ser chamado por outro workflow
    inputs:
      run-tests:
        required: false
        type: boolean
        default: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Copy sonar-project.properties from template
        run: |
          TEMPLATE=.github/ci/sonar-project-template.properties
          TARGET=sonar-project.properties
          if [ ! -f "$TARGET" ]; then
            cp "$TEMPLATE" "$TARGET"
            echo "Copied $TEMPLATE to $TARGET"
          else
            echo "$TARGET already exists, skipping copy"
          fi

      - name: Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner -Dsonar.token=$SONAR_TOKEN -Dsonar.host.url=http://host.docker.internal:9000

      # - name: Sonar Analysis (SonarCloud)
      #   uses: SonarSource/sonarcloud-github-action@v2
      #   with:
      #     projectBaseDir: .
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Run tests
      #   if: ${{ inputs.run-tests }}
      #   run: npm test
